apiVersion: v1
kind: ConfigMap
metadata:
  name: askpdf-config
data:
  AI_PROVIDER: gemini
  GEMINI_EMBEDDING_MODEL: gemini-embedding-001
  GEMINI_CHAT_MODEL: gemini-2.5-flash
  STORAGE_DRIVER: gcs
  GCS_BUCKET: YOUR_GCS_BUCKET
  GCS_PROJECT_ID: YOUR_PROJECT_ID
  GCS_PREFIX: pdf
  GCS_KEY_FILE: /var/secrets/gcs/key.json
